In [1]:
from pathlib import Path
import ipynbname
import pygwalker as pyg

REPO_ROOT = Path(ipynbname.path()).parent.parent
DATA_ROOT = REPO_ROOT / "data"

import pandas as pd
import geopandas as gpd
import fiona

In [ ]:
import geopandas as gpd

base = "https://mapy.geoportal.gov.pl/wss/service/rcn"

gdf_budynki = gpd.read_file("WFS:" +base, layer="budynki")
#gdf_lokale  = gpd.read_file("WFS:" +base, layer="lokale",  where="teryt = 1261")

In [ ]:
gdf_budynki

Empty GeoDataFrame
Columns: [gml_id, serwis_rcn, teryt, tran_przestrzen_nazw, tran_lokalny_id_iip, tran_wersja_id, tran_rodzaj_trans, tran_rodzaj_rynku, tran_sprzedajacy, tran_kupujacy, tran_cena_brutto, tran_vat, dok_data, nier_rodzaj, nier_prawo, nier_udzial, nier_pow_gruntu, nier_cena_brutto, nier_vat, bud_id_budynku, bud_nr_budynku, bud_rodzaj, bud_pow_uzyt, bud_cena_brutto, bud_vat, bud_adres, geometry]
Index: []

[0 rows x 27 columns]

In [8]:
import geopandas as gpd

base = "https://mapy.geoportal.gov.pl/wss/service/rcn"
# one powiat, one layer, one page:
url = (f"{base}?SERVICE=WFS&VERSION=2.0.0&REQUEST=GetFeature"
       f"&TYPENAMES=dzialki&COUNT=5000&STARTINDEX=0"
       f"&CQL_FILTER=teryt_powiatu='0261'")
gdf = gpd.read_file(url)

In [9]:
gdf

,gml_id,serwis_rcn,teryt,tran_przestrzen_nazw,tran_lokalny_id_iip,tran_wersja_id,tran_rodzaj_trans,tran_rodzaj_rynku,tran_sprzedajacy,tran_kupujacy,...,nier_vat,dzi_id_dzialki,dzi_nr_dzialki,dzi_przezn_wmpzp,dzi_pow_ewid,dzi_sposob_uzyt,dzi_cena_brutto,dzi_vat,dzi_adres,geometry
0,dzialki.96066543,None,3208,PL.PZGiK.4588.RCiWN,154ebe6a-88b1-42f0-b0f8-d1348fa568e9,2018-08-21T09:07:58,wolnyRynek,None,osobaPrawna,osobaFizyczna,...,None,320804_2.0002.254/77,254/77,None,1862,gruntyZabudowaneIZurbanizowane,None,None,None,"POLYGON ((271929.982 705336.246, 271931.94 705..."
1,dzialki.96066544,None,3208,PL.PZGiK.4588.RCiWN,154ebe6a-88b1-42f0-b0f8-d1348fa568e9,2018-08-21T09:07:58,wolnyRynek,None,osobaPrawna,osobaFizyczna,...,None,320804_2.0002.254/33,254/33,None,2890,gruntyZabudowaneIZurbanizowane,None,None,MSC:Grzybowo;UL:Piaskowa|MSC:Grzybowo;UL:Space...,"MULTIPOLYGON (((271825.831 705446.457, 271827...."
2,dzialki.96066545,None,3208,PL.PZGiK.4588.RCiWN,154ebe6a-88b1-42f0-b0f8-d1348fa568e9,2018-08-21T09:07:58,wolnyRynek,None,osobaPrawna,osobaFizyczna,...,None,320804_2.0002.359/1,359/1,None,1196,gruntyZabudowaneIZurbanizowane,None,None,MSC:Grzybowo;UL:Wydmowa,"POLYGON ((272035.469 705492.428, 272031.197 70..."
3,dzialki.96066546,None,3208,PL.PZGiK.4588.RCiWN,154ebe6a-88b1-42f0-b0f8-d1348fa568e9,2018-08-21T09:07:58,wolnyRynek,None,osobaPrawna,osobaFizyczna,...,None,320804_2.0002.368/17,368/17,None,1705,gruntyZabudowaneIZurbanizowane,None,None,MSC:Grzybowo;UL:Spacerowa,"POLYGON ((272056.931 705248.873, 272057.929 70..."
4,dzialki.96066547,None,3208,PL.PZGiK.4588.RCiWN,e26d4017-df7b-43f0-aa5a-0af89c2436a7,2019-01-22T15:08:25,wolnyRynek,None,osobaPrawna,osobaFizyczna,...,None,320801_1.0008.4/426,4/426,None,118,gruntyZabudowaneIZurbanizowane,None,None,MSC:Kołobrzeg;UL:Poleska,"POLYGON ((282624.546 708409.389, 282625.115 70..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,dzialki.97912049,None,1261,PL.PZGiK.4094.RCN,D0E3F9A3-720B-2DC3-E053-0C0A1EACECF0,2021-11-16T09:19:17,wolnyRynek,pierwotny,osobaPrawna,osobaFizyczna,...,None,126103_9.0001.109/8,109/8,None,0.7573,gruntyZabudowaneIZurbanizowane,None,None,MSC:KRAKÓW;UL:OSIEDLE PIASTÓW;NR_PORZ:56D|MSC:...,"POLYGON ((572822.256 248869.014, 572824.98 248..."
4996,dzialki.97912070,None,1261,PL.PZGiK.4094.RCN,D0E3F9A3-72C1-2DC3-E053-0C0A1EACECF0,2021-11-16T12:28:44,wolnyRynek,pierwotny,osobaPrawna,osobaFizyczna,...,None,126103_9.0001.362/6,362/6,None,0.0493,gruntyZabudowaneIZurbanizowane,None,None,MSC:KRAKÓW;UL:OSIEDLE PIASTÓW,"POLYGON ((572721.184 248870.786, 572722.255 24..."
4997,dzialki.97912071,None,1261,PL.PZGiK.4094.RCN,D0E3F9A3-72C1-2DC3-E053-0C0A1EACECF0,2021-11-16T12:28:44,wolnyRynek,pierwotny,osobaPrawna,osobaFizyczna,...,None,126103_9.0001.109/8,109/8,None,0.7573,gruntyZabudowaneIZurbanizowane,None,None,MSC:KRAKÓW;UL:OSIEDLE PIASTÓW;NR_PORZ:56D|MSC:...,"POLYGON ((572822.256 248869.014, 572824.98 248..."
4998,dzialki.97912080,None,1261,PL.PZGiK.4094.RCN,D0E3F9A3-7319-2DC3-E053-0C0A1EACECF0,2021-11-16T13:24:32,wolnyRynek,pierwotny,osobaPrawna,osobaFizyczna,...,None,126103_9.0001.362/6,362/6,None,0.0493,gruntyZabudowaneIZurbanizowane,None,None,MSC:KRAKÓW;UL:OSIEDLE PIASTÓW,"POLYGON ((572721.184 248870.786, 572722.255 24..."
4999,dzialki.97912081,None,1261,PL.PZGiK.4094.RCN,D0E3F9A3-7319-2DC3-E053-0C0A1EACECF0,2021-11-16T13:24:32,wolnyRynek,pierwotny,osobaPrawna,osobaFizyczna,...,None,126103_9.0001.109/8,109/8,None,0.7573,gruntyZabudowaneIZurbanizowane,None,None,MSC:KRAKÓW;UL:OSIEDLE PIASTÓW;NR_PORZ:56D|MSC:...,"POLYGON ((572822.256 248869.014, 572824.98 248..."