In [1]:
from pathlib import Path
import ipynbname

REPO_ROOT = Path(ipynbname.path()).parent.parent
DATA_ROOT = REPO_ROOT / "data"

import pandas as pd
import geopandas as gpd

In [2]:
budynki = gpd.read_file(DATA_ROOT / "raw" / "floorspace" / "budynki.gpkg")
lokale = gpd.read_file(DATA_ROOT / "raw" / "floorspace" / "lokale.gpkg")
dzialki = gpd.read_file(DATA_ROOT / "raw" / "floorspace" / "dzialki.gpkg")
budynki.head()

,gml_id,serwis_rcn,teryt,tran_przestrzen_nazw,tran_lokalny_id_iip,tran_wersja_id,tran_rodzaj_trans,tran_rodzaj_rynku,tran_sprzedajacy,tran_kupujacy,...,nier_cena_brutto,nier_vat,bud_id_budynku,bud_nr_budynku,bud_rodzaj,bud_pow_uzyt,bud_cena_brutto,bud_vat,bud_adres,geometry
0,budynki.46006117,NaN,1209,PL.PZGiK.0000.RCiWN,7588edc4-6424-4251-976b-54904284524e,2026-06-24T12:56:14,wolnyRynek,wtorny,osobaFizyczna,osobaFizyczna,...,NaN,NaN,120908_2.0006.20_BUD,20_BUD,mieszkalny,NaN,NaN,NaN,MSC:Zawadka;NR_PORZ:87,"MULTIPOLYGON (((562998.813 211273.376, 562991...."
1,budynki.46006268,NaN,1209,PL.PZGiK.0000.RCiWN,92faf01b-65c6-4f1b-83e8-1c0e25f669b0,2026-05-25T10:26:29,wolnyRynek,wtorny,osobaPrawna,osobaFizyczna,...,NaN,NaN,120902_2.0001.1447_BUD,1447_BUD,mieszkalny,NaN,NaN,NaN,MSC:Lubień;NR_PORZ:957,"MULTIPOLYGON (((569246.081 204906.579, 569255...."
2,budynki.46006345,NaN,1209,PL.PZGiK.0000.RCiWN,7588edc4-6424-4251-976b-54904284524e,2026-06-24T12:56:14,wolnyRynek,wtorny,osobaFizyczna,osobaFizyczna,...,NaN,NaN,120908_2.0006.22_BUD,22_BUD,gospodarczy,NaN,NaN,NaN,NaN,"MULTIPOLYGON (((562998.84 211291.132, 562992.1..."
3,budynki.46006582,NaN,1217,PL.PZGiK.0000.RCiWN,441329aa-d5fa-4e7d-95da-38439b239738,2026-06-22T10:17:37,wolnyRynek,wtorny,osobaPrawna,osobaFizyczna,...,NaN,NaN,121704_2.0401.4821_BUD,4821_BUD,mieszkalny,NaN,NaN,NaN,MSC:Kościelisko;UL:Groń;NR_PORZ:22G,"MULTIPOLYGON (((563291.802 157886.439, 563291...."
4,budynki.46006595,NaN,1217,PL.PZGiK.0000.RCiWN,4828f310-9557-4efd-8606-d3b989ac31c2,2026-06-08T09:40:56,wolnyRynek,pierwotny,osobaFizyczna,osobaFizyczna,...,974160,182160,121703_2.0302.2971_BUD,2971_BUD,pozostaleNiemieszkalne,NaN,NaN,NaN,MSC:Białka Tatrzańska;UL:Środkowa;NR_PORZ:158H,"MULTIPOLYGON (((580205.503 169230.158, 580212...."

In [3]:
dzialki.head()

,gml_id,serwis_rcn,teryt,tran_przestrzen_nazw,tran_lokalny_id_iip,tran_wersja_id,tran_rodzaj_trans,tran_rodzaj_rynku,tran_sprzedajacy,tran_kupujacy,...,nier_vat,dzi_id_dzialki,dzi_nr_dzialki,dzi_przezn_wmpzp,dzi_pow_ewid,dzi_sposob_uzyt,dzi_cena_brutto,dzi_vat,dzi_adres,geometry
0,dzialki.36870253,None,1217,PL.PZGiK.0000.RCiWN,f605c445-e070-480f-af66-cfe967ebae63,2016-02-16T17:47:12,wolnyRynek,NaN,osobaPrawna,osobaFizyczna,...,NaN,121701_1.0006.192/1,192/1,NaN,4775,gruntyZabudowaneIZurbanizowane,NaN,NaN,MSC:Zakopane,"MULTIPOLYGON (((569519.441 159743.196, 569539...."
1,dzialki.36870863,None,1217,PL.PZGiK.0000.RCiWN,0364b113-cae2-476d-a57a-30344233e856,2017-03-27T13:01:37,wolnyRynek,NaN,osobaFizyczna,osobaFizyczna,...,NaN,121701_1.0153.326,326,NaN,965,gruntyZabudowaneIZurbanizowane,NaN,NaN,NaN,"MULTIPOLYGON (((566479.742 157620.893, 566489...."
2,dzialki.36870864,None,1217,PL.PZGiK.0000.RCiWN,0364b113-cae2-476d-a57a-30344233e856,2017-03-27T13:01:37,wolnyRynek,NaN,osobaFizyczna,osobaFizyczna,...,NaN,121701_1.0153.325,325,NaN,914,gruntyZabudowaneIZurbanizowane,NaN,NaN,MSC:Zakopane;UL:Przewodnika Józefa Krzeptowski...,"MULTIPOLYGON (((566451.074 157609.048, 566453...."
3,dzialki.36870310,None,1217,PL.PZGiK.0000.RCiWN,696d2f02-8fc2-4622-ab70-a6420cedacf2,2018-04-13T10:00:50,wolnyRynek,NaN,osobaPrawna,osobaFizyczna,...,NaN,121701_1.0006.483,483,NaN,594,gruntyZabudowaneIZurbanizowane,NaN,NaN,MSC:Zakopane;UL:Nowotarska;NR_PORZ:24,"MULTIPOLYGON (((569640.638 159723.141, 569624...."
4,dzialki.36870935,None,1217,PL.PZGiK.0000.RCiWN,873c4b52-ddab-4f6e-9c8f-ae2ebf2bcfa3,2017-09-26T10:54:04,wolnyRynek,NaN,osobaPrawna,osobaPrawna,...,NaN,121701_1.0168.24/4,24/4,NaN,1689,gruntyZabudowaneIZurbanizowane,NaN,NaN,MSC:Zakopane;UL:Oswalda Balzera;NR_PORZ:21F,"MULTIPOLYGON (((571748.43 158022.623, 571751.2..."

In [5]:
# data column = dok_data -> transform to datetime (orignal format e.g.: 2022-10-24 02:00:00+02)
# price column = tran_cena_brutto -> transform to float
# -> remove rows where price is 0 or np.nan

budynki['tran_cena_brutto'] = budynki['tran_cena_brutto'].astype(float)
budynki = budynki[budynki['tran_cena_brutto'] > 0]
budynki = budynki[budynki['tran_cena_brutto'].notna()]

lokale['tran_cena_brutto'] = lokale['tran_cena_brutto'].astype(float)
lokale = lokale[lokale['tran_cena_brutto'] > 0]
lokale = lokale[lokale['tran_cena_brutto'].notna()]

dzialki['nier_cena_brutto'] = dzialki['nier_cena_brutto'].astype(float)
dzialki = dzialki[dzialki['nier_cena_brutto'] > 0]
dzialki = dzialki[dzialki['nier_cena_brutto'].notna()]

# take first 10 characters from dok_data and transform to datetime
budynki['dok_data'] = pd.to_datetime(budynki['dok_data'].str[:10])
lokale['dok_data'] = pd.to_datetime(lokale['dok_data'].str[:10])
dzialki['dok_data'] = pd.to_datetime(dzialki['dok_data'].str[:10])

# and transfort YYYY-MM-DD to datetime
budynki['dok_data'] = pd.to_datetime(budynki['dok_data'], format='%Y-%m-%d')
lokale['dok_data'] = pd.to_datetime(lokale['dok_data'], format='%Y-%m-%d')
dzialki['dok_data'] = pd.to_datetime(dzialki['dok_data'], format='%Y-%m-%d')

In [6]:
print(budynki['nier_rodzaj'].value_counts())
print(lokale['nier_rodzaj'].value_counts())
print(dzialki['nier_rodzaj'].value_counts())

nier_rodzaj
nieruchomoscLokalowa                 4677235
nieruchomoscGruntowaZabudowana       1383934
nieruchomoscBudynkowa                  35463
nieruchomoscGruntowaNiezabudowana      30991
Name: count, dtype: int64
nier_rodzaj
nieruchomoscLokalowa                 2562479
nieruchomoscGruntowaZabudowana         10232
nieruchomoscGruntowaNiezabudowana        701
nieruchomoscBudynkowa                    606
Name: count, dtype: int64
nier_rodzaj
nieruchomoscLokalowa                 2904783
nieruchomoscGruntowaNiezabudowana    1604539
nieruchomoscGruntowaZabudowana        551390
nieruchomoscBudynkowa                  13091
Name: count, dtype: int64

In [8]:
gminy = gpd.read_file(DATA_ROOT / "raw" / "shapefiles" / "PRG_jednostki_administracyjne_2021" / "A03_Granice_gmin.shp")
gminy['teryt'] = gminy['JPT_KOD_JE'].astype(str)

short_gminy = gminy[['teryt', 'JPT_NAZWA_', 'geometry']]

# Spatial join budynki with short_gminy
budynki = gpd.sjoin(budynki.to_crs(short_gminy.crs), short_gminy, how='left', predicate='within')
lokale = gpd.sjoin(lokale.to_crs(short_gminy.crs), short_gminy, how='left', predicate='within')
dzialki = gpd.sjoin(dzialki.to_crs(short_gminy.crs), short_gminy, how='left', predicate='within')

In [14]:
bud_teryt = pd.DataFrame(budynki['teryt_right'].value_counts())
lok_teryt = pd.DataFrame(lokale['teryt_right'].value_counts())
dz_teryt = pd.DataFrame(dzialki['teryt_right'].value_counts())

bud_teryt.columns = ['budynki']
lok_teryt.columns = ['lokale']
dz_teryt.columns = ['dzialki']

In [16]:
dz_teryt

             dzialki
teryt_right
1465011       671326
2261011       311807
2061011       276282
0663011       190636
1261011       156096
...              ...
2014022            1
0405022            1
2213021            1
2213052            1
2804032            1

[2369 rows x 1 columns]

In [ ]:
budynki['teryt'].sort_values().unique()